### PR TITLE
Rename _abbr properties to _a

### PR DESCRIPTION
**Pull request by dianashk**
- [x] Add nice new travis setup
- [x] Add integration tests to travis setup
- [x] Rename new admin properties with `_abbr` to `_a` (leave old `admin1_abbr` alone)
- [x] Fix integration test for bounding box

Connected to pelias/api#424
Connects pelias/pelias#258

### CODE REVIEW

**Comment by trescube** [comment]
:+1:

**Comment by missinglink** [comment]
what was the thinking behind changing the variable name from 'abbr' to 'a'?

it doesn't matter much what it's called, I just wanted to point out that to external contributors and the uninitiated a variable named 'a' might be confused to mean something else.

**Comment by orangejulius** [comment]
:+1: and also hooray for more testing on travis!

**Comment by dianashk** [comment]
$ npm publish
+ pelias-schema@3.0.0

**Comment by dianashk** [comment]
```
$ npm publish
+ pelias-schema@3.0.0
```

**Pull request merged**
