### PR TITLE
add popularity field

### PR DESCRIPTION
**Pull request by hkrishna**
Popularity score can be computed based on number of photos taken, number of visitors to a region/point etc

This will be useful with respect to https://github.com/pelias/admin-lookup/issues/5

Fixes pelias/pelias#51

### CODE REVIEW

**Comment by hkrishna** [comment]
Connected to pelias/api#71

**Comment by missinglink** [comment]
please add info to `README.md`

**Comment by hkrishna** [comment]
@missinglink can you elaborate on what you would like to see in README.md? Currently, we have no mention of the specific document fields in the readme..

**Comment by missinglink** [comment]
Sorry, got mixed up with pelias/model

+1

**Pull request merged**
