### PR TITLE
added a bunch of new street types culled from tiger data and my memory

### LINKED ISSUE #75: Update street_suffix.js with additional types
Pull all street types from Tiger data using ftp://ftp2.census.gov/geo/tiger/TIGER2015/FEATNAMES/

### PR DESCRIPTION
**Pull request by stephenkhess**
Fixed #75

### CODE REVIEW

**Comment by riordan** [comment]
Are there any other expansions or types we want to include? [Libpostal](https://github.com/openvenues/libpostal) adds quite a few more across several languages ([English](https://github.com/openvenues/libpostal/blob/master/resources/dictionaries/en/street_types.txt)).

Also there are more than one kind of expansion. Do we want to incorporate multiple expansions?

**Comment by stephenkhess** [comment]
I can add more from libpostal but AFAIK, we only support a 1-1 relationship on full name -> abbreviation, so "bayou" can only map to "byu" *or* "bayoo", but not both.

**Comment by missinglink** [comment]
:+1: nice. I can see the unit tests failed on Travis, could you check them out locally by running `npm test`

**Comment by stephenkhess** [comment]
D'oh!  Didn't occur to me that there even would be unit tests, will fix now.

**Comment by missinglink** [comment]
LGTM :+1:

**Pull request merged**
