### PR TITLE
Remove peliasQueryFullToken analyzer

### PR DESCRIPTION
**Pull request by Joxit**
Since we merged our beloved pelias parser, this analyser is no more used :wave:.

### CODE REVIEW

**Comment by missinglink** [comment]
Can we also remove `peliasQueryPartialToken` and `partial_token_address_suffix_expansion` along with any synonyms?

**Comment by missinglink** [comment]
More info on this PR: https://github.com/pelias/schema/pull/370

**Comment by Joxit** [comment]
Oh yes, I forgot these two :smile: updated and I have not forgotten the integration tests :sweat_smile:

**Comment by missinglink** [comment]
Ok so since https://github.com/pelias/api/pull/1330 was merged 5 months ago, I think that's enough of a deprecation window, these fields are now redundant and removing them cleans up the schema a bunch.

**Comment by orangejulius** [comment]
Wow `-900` lines! :clap:

**Comment by missinglink** [comment]
Yeah and 140 from the schema file itself!

**Pull request merged**
