### PR TITLE
add github actions workflow to replace travis

### PR DESCRIPTION
**Pull request by missinglink**
Add config from https://github.com/pelias/api/pull/1495 in another repo with a different testing requirement (build matrix, external database).

### CODE REVIEW

**Comment by missinglink** [comment]
This PR had some messy commits, I've cleaned it up now and opened the PR up for review/merging.

**Comment by missinglink** [comment]
note: at time of writing there is an outage which may affect the checks:
https://github.com/pelias/openaddresses/pull/478#issuecomment-768800427

**Comment by orangejulius** [comment]
This one doesn't remove `.travis.yml`, is that intentional?

**Comment by missinglink** [comment]
> This one doesn't remove `.travis.yml`, is that intentional?

Yes/No ⚖️, initially it seemed best to leave both CI systems running, but since we've now lived with Actions a while and not had any issues we might consider removing `.travis.yml` here and also https://github.com/pelias/api where I left it during the first PR.

**Comment by missinglink** [comment]
I removed `.travis.yml` via rebase

**Comment by missinglink** [comment]
I've set the CI actions to be `required` before merging a PR, any PRs authored before this was merged will require a rebase.

**Pull request merged**
