### PR TITLE
elasticsearch 7

### PR DESCRIPTION
**Pull request by missinglink**
es7 compatibility (breaks compatibility with es5)

notable changes:
- changes inherited from https://github.com/pelias/schema/pull/385
- ~~moved 'word delimiter' filter below synonyms filter to avoid `message [failed to create index], failure [IllegalArgumentException[Token filter [word_delimiter] cannot be used to parse synonyms]]` error~~ (backported to master already)
- ~~changed the `_type` from "doc" to "_doc" (as required in ES7)~~ superseded by https://github.com/pelias/config/pull/119
- added a helper to deal with the new `hits.total` format

todo:
- [x] decide on whether we remove `word_delimiter` ~~or move it down below the synonyms~~
- [x] squash the commits and/or add a breaking change commit message
- [x] update `pelias/config` to set the default `schema.typeName` to `_doc` (done in https://github.com/pelias/pelias/issues/831)
- [x] ~~update `pelias/model` to use the `_doc` type instead of `doc`~~ (see above)
- [x] ~~update all the importers to use the updated `pelias/model` version~~ (also no longer relevant)

### CODE REVIEW

**Comment by orangejulius** [comment]
See also https://github.com/pelias/schema/pull/392

**Comment by missinglink** [comment]
I suspect this is failing due to a [lack of support for typeless indices in the legacy elasticsearch-js client](https://github.com/elastic/elasticsearch-js/issues/802).

It might be easier to change back to a single type (called `_doc` or whatever) to make the interoperability between 6 & 7 easier.

**Comment by missinglink** [comment]
okay, I rewrote this as still containing a single type called `_doc` and it's now compatible with ES6 & ES7

**Comment by missinglink** [comment]
build passing! woohoo! compatibility dance 🕺 👯

**Comment by missinglink** [comment]
So.. while this schema works great to create an index on ES6/ES7 the importers all fail due to [this line in pelias/model](https://github.com/pelias/model/blob/master/Document.js#L149) which assumes the type is named `doc` instead of `_doc`.

It's kinda unfortunate but correct to do it like this, we must continue with the type named `doc` for as long as we support ES5 (due to the lack of support for underscores in 5).

Once we drop backwards support for 5 we can go ahead and change that line in `pelias/model`, it, unfortunately, makes this hard to test in the meantime.

**Comment by orangejulius** [comment]
I've just rebased this branch against master after extracting the [hits helper](https://github.com/pelias/schema/pull/417) to a separate PR. The list of changes is getting pretty small, and after #418 I bet we can even remove more.

**Comment by orangejulius** [comment]
All aspects of this PR have now been extracted into or otherwise handled by the following PRs:

- https://github.com/pelias/schema/pull/417
- https://github.com/pelias/schema/pull/418
- https://github.com/pelias/schema/pull/420
- https://github.com/pelias/schema/pull/421
- https://github.com/pelias/schema/pull/422
- https://github.com/pelias/schema/pull/423
- https://github.com/pelias/schema/pull/424
- https://github.com/pelias/schema/pull/425

Referring to this PR and splitting it up into component pieces was a super useful exercise in making sure we have all our ES7 bases covered. And now we do! :tada:

**Pull request closed without merging**
