### PR TITLE
[discuss] simplify the schema to a single mapping

### PR DESCRIPTION
**Pull request by missinglink**
Following on from the discussion here: https://github.com/pelias/schema/issues/51

This is a proposal to simplify the schema to a **single mapping**.

In effect this combines the previous mappings named `poi` and `admin` to a more generic mapping named `document`.

### CODE REVIEW

**Comment by sevko** [comment]
I like it.

**Comment by missinglink** [comment]
resolves: https://github.com/pelias/schema/issues/51

**Comment by sevko** [comment]
+1

@dianashk / @hkrishna should both look over this as well.

**Comment by hkrishna** [comment]
:+1: looks good

**Comment by dianashk** [comment]
:+1:

**Comment by missinglink** [comment]
```bash
$ npm publish
npm http PUT https://registry.npmjs.org/pelias-schema
npm http 200 https://registry.npmjs.org/pelias-schema
+ pelias-schema@0.3.0
```

**Comment by bradh** [comment]
Should this be closed as of https://github.com/pelias/schema/commit/5430f250f5dcd7ab6c593f951a1b91e5ed0f9ee8 ? If not, what is still remaining?

**Comment by dianashk** [comment]
@bradh This has been merged, so it is effectively closed.

**Pull request merged**
