### PR TITLE
Fix for pelias/api#1077

### PR DESCRIPTION
**Pull request by Joxit**
Fail to search `Saint..` cities in structured queries

Add synonym for saint and sainte

### CODE REVIEW

**Comment by orangejulius** [comment]
Hi @Joxit.
I _think_ this looks good. It's honestly been a while since we've touched this code, and it's quite tricky to ensure synonyms don't have unexpected side effects, especially with autocomplete. However, because this only affects admin area analysers, which we will likely stop using soon for autocomplete (to be replaced by much improved admin area support from [Placeholder](https://github.com/pelias/placeholder), I doubt there are any possible problems. I even went so far as to find a case where an address exists in St Louis and other cities:

[/v1/autocomplete?text=1443 park ave, saint louis](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=1443%20park%20ave,%20saint%20louis). I tried all the combinations of abbreviations I could think of. The bad news is we already don't do a great job, the good news is that means we probably can't break it further :)

I'd love for @missinglink to chime in on this and https://github.com/pelias/api/issues/1077 but it looks good to me!

**Comment by Joxit** [comment]
Any news on this? This will be outdated with  #272

**Comment by missinglink** [comment]
I @Joxit, you caught us in a time of transition!

I just cleaned up the synonyms, standardizing them to the solr file format (and putting them in their own files) in https://github.com/pelias/schema/pull/272.

In https://github.com/pelias/schema/pull/273 I added the ability for users to add their own custom synonyms. (today I added support for 'admin' as well as for 'name' and 'street').

I opened https://github.com/pelias/schema/pull/274 today to address this issue, it adds your synonyms to the `synonyms/custom_admin.txt` file and I added a couple more too. I also change them to be synonyms instead of substitutions (using a comma instead of `=>`).

Let me know what you think?
Sorry, I wasn't able to rebase your commits, the history was getting too crazy!

**Comment by Joxit** [comment]
Hi @missinglink, Yeah I saw your refactoring :wink: 

It looks good to me. Nice job, I saw that you added fort and mount too.

The next step will be to clean `pelias-api/sanitizer/_city_name_standardizer.js` that's it ? (to keep only `whitespace_normalized`)

**Comment by orangejulius** [comment]
@Joxit I agree. I think https://github.com/pelias/api/pull/767 which added that custom and america-centric handling of mt/st/fort can be mostly resolved with some of the alias work we're doing and proper updates to data in WOF

**Comment by trescube** [comment]
The city name standardize stuff should go away, it's a relic of a time whe  we flirted with the idea of pulling analysis out of ES and into code.

**Comment by orangejulius** [comment]
Hey, it solved some problems. And I think we may still pull more analysis out to make it replicable elsewhere.

**Comment by Joxit** [comment]
@orangejulius this is a good idea.

**Comment by missinglink** [comment]
changes merged in https://github.com/pelias/schema/pull/274, thanks for your contribution!

**Pull request closed without merging**
