### PR TITLE
expand umlauts

### PR DESCRIPTION
**Pull request by missinglink**
[DO NOT MERGE] at this time

``` javascript
"umlaut" : {
  "type" : "mapping",
  "mappings" : [
    "ä=>ae",
    "ö=>oe",
    "ü=>ue",
    "Ä=>Ae",
    "Ö=>Oe",
    "Ü=>Ue",
    "ß=>ss"
  ]
}
```

closes https://github.com/pelias/schema/issues/74
closes https://github.com/pelias/pelias/issues/319

### CODE REVIEW

**Comment by missinglink** [comment]
Fun fact of the day:

In Germany, A Big Mac used to be a Big Mäc.

And the Filet-o-Fish was the Fishmäc. The spelling with the umlaut actually gets German speakers a little closer to the English pronunciation of “Mac.” But in 2007 McDonald’s took away the umlauts, and now Germans have to get boring ol’ Big Macs like the rest of us.

pulp

**Comment by missinglink** [comment]
This PR would break some existing behavior, eg:

records indexed as `Österreich` would be query-able using the input `Oesterreich` but not `Osterreich`.

prior to this PR the term `Österreich` was retrievable using the term `Osterreich` so this would be a breaking change.

It seems like a better strategy would be to import two versions of the same token; once as `Oesterreich` and once as `Osterreich`.

**Comment by orangejulius** [comment]
Do we want to close this PR in favor of something icu related?

**Comment by missinglink** [comment]
I don't believe the ICU library will handle this type of expansion.

**Comment by missinglink** [comment]
This feature will require alt-names as the country name above can have 3 forms:

```
Österreich
Oesterreich
Osterreich
```

moving to alt-names feature as it can only be solved for a maximum of 2 cases before then.

**Comment by trescube** [comment]
Closed due to teh new [hotness](pelias/placeholder)

**Pull request closed without merging**
