### PR TITLE
simplify schema to use _default_ mapping

### PR DESCRIPTION
**Pull request by missinglink**
this PR aims to completely simplify the schema, using the `_default_` mapping on the `pelias` elasticsearch index means that all new `_type`'s created will inherit their mappings from `_default_`.

in effect this makes creating a new `_type` for a new dataset a no-brainer, completely removing the need for messing around in this repo to add the new mapping and then running a script.

I tested it out here: https://github.com/pelias/playground/blob/master/default_mapping.js#L80 and it behaved as expected, plus I did an OSM import and it worked fine, the `osm*` layers inherited their mappings from `_default_`

### CODE REVIEW

**Comment by hkrishna** [comment]
looks good :+1:

**Comment by dianashk** [comment]
:+1:

**Comment by missinglink** [comment]
resolves https://github.com/pelias/schema/issues/48

**Comment by missinglink** [comment]
```bash
$ npm publish
npm http PUT https://registry.npmjs.org/pelias-schema
npm http 200 https://registry.npmjs.org/pelias-schema
+ pelias-schema@0.4.0
```

**Pull request merged**
